### PR TITLE
Initializing Select2

### PR DESCRIPTION
**Pull request by dborovsky**
I have added initilazing select2, mapper class for select2.

fixing decorator for tag_list has not yet done.

### CODE REVIEW

**Comment by Mehonoshin** [comment]
Fix build pls

**Comment by dborovsky** [comment]
Не проходят тесты eslint:
```
/home/borowskiy/projects/juniorjobs.ru/app/assets/javascripts/components/select2_initializer.js
   1:1   error  Use the function form of 'use strict'  strict
   3:28  error  Use the function form of 'use strict'  strict
   9:5   error  '$' is not defined                     no-undef
  16:22  error  '_' is not defined                     no-undef
  46:1   error  '$' is not defined                     no-undef
  46:3   error  Use the function form of 'use strict'  strict
  47:14  error  'Select2Initializer' is not defined    no-undef

/home/borowskiy/projects/juniorjobs.ru/app/assets/javascripts/initializers/select2.js
  1:25  error  'Select2Initializer' is not defined 
```

**Comment by Mehonoshin** [comment]
@khusnetdinov check pls

**Comment by khusnetdinov** [comment]
Будем переделывать вдвоем

**Pull request closed without merging**
